linestorm_cms_module_post_admin_list:
    pattern:  /
    defaults: { _controller: LineStormPostBundle:Admin:list }

linestorm_cms_module_post_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormPostBundle:Admin:edit }
    requirements:
       id: \d+

linestorm_cms_module_post_admin_view:
    pattern:  /{id}
    defaults: { _controller: LineStormPostBundle:Admin:view }
    requirements:
       id: \d+

linestorm_cms_module_post_admin_create:
    pattern:  /new
    defaults: { _controller: LineStormPostBundle:Admin:new }
